[project]
name = "mcp-server"
version = "0.1.0"
description = "Toy Project for MCP Server"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.6",
    "pillow>=11.3.0",
    "requests>=2.32.4",
]
